import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';

import { checkCodeowners, renderCodeowners } from '../scripts/build-codeowners.js';

test('each profile becomes a CODEOWNERS rule for its own admins', () => {
  const output = renderCodeowners([
    { slug: 'river-song', profile: { admins: ['charles2ke', 'someone-else'] } },
    { slug: 'ada', profile: { admins: ['ada'] } },
  ]);
  assert.match(output, /^\/profiles\/ada\.json @ada$/m);
  assert.match(output, /^\/profiles\/river-song\.json @charles2ke @someone-else$/m);
  // Sorted by slug so the file only changes when the profiles do.
  assert.ok(output.indexOf('/profiles/ada.json') < output.indexOf('/profiles/river-song.json'));
});

test('profiles without admins produce no rule', () => {
  const output = renderCodeowners([
    { slug: 'nobody', profile: {} },
    { slug: 'empty', profile: { admins: [] } },
  ]);
  assert.ok(!output.includes('/profiles/'));
  assert.match(output, /No profile currently names an admin/);
});

test('admins that are not usernames never reach CODEOWNERS', () => {
  // Validation rejects these, but the generator writes a file that grants review
  // rights, so it refuses to pass anything odd through on its own account.
  const output = renderCodeowners([
    { slug: 'x', profile: { admins: ['good', '@bad', 'has space', 'bad\nuser', 7, null, '-nope'] } },
  ]);
  assert.match(output, /^\/profiles\/x\.json @good$/m);
  assert.ok(!output.includes('@bad'));
  assert.ok(!output.includes('has space'));
  assert.ok(!output.includes('nope'));
});

test('a repeated admin is listed once', () => {
  const output = renderCodeowners([{ slug: 'x', profile: { admins: ['Ada', 'ada', 'ADA'] } }]);
  assert.match(output, /^\/profiles\/x\.json @Ada$/m);
});

test('the committed CODEOWNERS matches the profiles in this repository', async () => {
  const { upToDate } = await checkCodeowners();
  assert.ok(upToDate, 'run `npm run codeowners` and commit the result');
});

test('the committed CODEOWNERS says it is generated', async () => {
  const file = await readFile(new URL('../.github/CODEOWNERS', import.meta.url), 'utf8');
  assert.match(file, /Generated by `npm run codeowners`/);
});
