import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';

import { MAINTAINERS, checkCodeowners, renderCodeowners } from '../scripts/build-codeowners.js';

test('each profile becomes a CODEOWNERS rule for its own admins', () => {
  const output = renderCodeowners([
    { slug: 'river-song', profile: { admins: ['charles2ke', 'someone-else'] } },
    { slug: 'ada', profile: { admins: ['ada'] } },
  ]);
  assert.match(output, /^\/profiles\/ada\.json @ada$/m);
  assert.match(output, /^\/profiles\/river-song\.json @charles2ke @someone-else$/m);
  // Sorted by slug so the file only changes when the profiles do.
  assert.ok(output.indexOf('/profiles/ada.json') < output.indexOf('/profiles/river-song.json'));
});

test('profiles without admins produce no rule', () => {
  const output = renderCodeowners([
    { slug: 'nobody', profile: {} },
    { slug: 'empty', profile: { admins: [] } },
  ]);
  assert.ok(!output.includes('/profiles/'));
  assert.match(output, /No profile currently names an admin/);
});

test('admins that are not usernames never reach CODEOWNERS', () => {
  // Validation rejects these, but the generator writes a file that grants review
  // rights, so it refuses to pass anything odd through on its own account.
  const output = renderCodeowners([
    { slug: 'x', profile: { admins: ['good', '@bad', 'has space', 'bad\nuser', 7, null, '-nope'] } },
  ]);
  assert.match(output, /^\/profiles\/x\.json @good$/m);
  assert.ok(!output.includes('@bad'));
  assert.ok(!output.includes('has space'));
  assert.ok(!output.includes('nope'));
});

test('a repeated admin is listed once', () => {
  const output = renderCodeowners([{ slug: 'x', profile: { admins: ['Ada', 'ada', 'ADA'] } }]);
  assert.match(output, /^\/profiles\/x\.json @Ada$/m);
});

test('a file name that is not a slug never reaches CODEOWNERS', () => {
  // File names come from the directory listing and are chosen by whoever opens
  // the pull request. A newline in one would write rules of its own into a file
  // that decides who may approve changes, so the slug is checked like the
  // admins are.
  const output = renderCodeowners([
    { slug: 'x\n* @attacker\ny', profile: { admins: ['victim'] } },
    { slug: '../escape', profile: { admins: ['victim'] } },
    { slug: 'Upper Case', profile: { admins: ['victim'] } },
    { slug: 7, profile: { admins: ['victim'] } },
    { slug: 'fine', profile: { admins: ['victim'] } },
  ]);
  assert.match(output, /^\/profiles\/fine\.json @victim$/m);
  assert.ok(!output.includes('@attacker'));
  assert.ok(!output.includes('escape'));
  assert.ok(!output.includes('Upper Case'));
  // Only the header comments and the one good rule: nothing else got a line.
  const rules = output.split('\n').filter((line) => line.startsWith('/profiles/'));
  assert.deepEqual(rules, ['/profiles/fine.json @victim']);
});

test('the maintainers own this file and the script that writes it', () => {
  // Without these rules a pull request could delete the profile rules, or change
  // the script that writes them, with no profile owner having to approve it.
  const output = renderCodeowners([{ slug: 'x', profile: { admins: ['victim'] } }]);
  const owners = MAINTAINERS.map((maintainer) => `@${maintainer}`).join(' ');
  assert.ok(MAINTAINERS.length > 0);
  assert.match(output, new RegExp(`^/\\.github/ ${owners}$`, 'm'));
  assert.match(output, new RegExp(`^/scripts/build-codeowners\\.js ${owners}$`, 'm'));
  // Last matching rule wins, so they come after the profile rules.
  assert.ok(output.indexOf('/profiles/x.json') < output.indexOf('/.github/'));
});

test('the maintainer rules survive a repository with no profiles at all', () => {
  const output = renderCodeowners([]);
  assert.match(output, /^\/\.github\/ @/m);
});

test('the committed CODEOWNERS matches the profiles in this repository', async () => {
  const { upToDate } = await checkCodeowners();
  assert.ok(upToDate, 'run `npm run codeowners` and commit the result');
});

test('the committed CODEOWNERS says it is generated', async () => {
  const file = await readFile(new URL('../.github/CODEOWNERS', import.meta.url), 'utf8');
  assert.match(file, /Generated by `npm run codeowners`/);
});

test('the committed CODEOWNERS protects itself', async () => {
  const file = await readFile(new URL('../.github/CODEOWNERS', import.meta.url), 'utf8');
  assert.match(file, /^\/\.github\/ @/m);
});
